site_name: Keras-vis Documentation
theme: readthedocs
docs_dir: templates
site_description: 'Documentation for keras-vis, neural network visualization toolkit.'

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

pages:
  - Home: index.md
  - Core API:
    - losses: vis.losses.md
    - regularizers: vis.regularizers.md
    - optimizer: vis.optimizer.md
    - visualization: vis.visualization.md
  - Utils:
    - utils: vis.utils.utils.md
    - vggnet: vis.utils.vggnet.md
